### ISSUE TITLE
FIx server_dictionary.json being overwritten

### ISSUE THREAD

**Issue by nathen418** [Antares-Network/BASM#1]
the file keeps being overwritten by new data each time a server is added, rather than the data being appended to the file.

It should look something like this when done 
Currently looks like this:
![](https://cdn.discordapp.com/attachments/761045738770792488/853366316526075964/unknown.png)
It should look something like this when done 
![](https://cdn.discordapp.com/attachments/794605620740489236/852595106472656916/unknown.png)

Reference:
https://github.com/Antares-Network/BASM/blob/development/src/main/java/com/antares/basm/Entry.java
https://github.com/Antares-Network/BASM/blob/development/src/main/java/com/antares/basm/ServerCreator.java

**Comment by piotrwyrw** [comment]
The implemented fix is yet to be verified
